lm:
  host: lm
  project: xxx
  user-api-log: true

app:
  test: test

server:
  port: 8080
  servlet:
    encoding:
      charset: utf-8
      enabled: true
      force: true

spring:
  #
  jackson:
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 5GB
      max-request-size: 5GB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    #按需求修改
    url: jdbc:mysql://xxx:3306/xx?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username:
    password:
    hikari:
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 600000
      pool-name: DataSourceHikariCP
      max-lifetime: 1800000
      connection-test-query: select 1
  data:
    redis:
      repositories:
        enabled: false
      database: 1
      host: lm
      port: 6379
      password:
      lettuce:
        lettuce:
          pool:
            max-active: 8
            max-idle: 8
            max-wait: -1
            min-idle: 0
    elasticsearch:
      uris: elasticsearch:9200
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.lm.springbootstandardproject.model
  configuration:
    map-underscore-to-camel-case: false
    call-setters-on-nulls: true

swagger:
  enabled: true
